name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract ngrok
      run: Expand-Archive ngrok.zip

    - name: Authenticate ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Create ngrok tunnel for RDP
      run: .\ngrok\ngrok.exe tcp 3389

    - name: Download VMware Workstation
      run: Invoke-WebRequest "https://pubdl.hausmer.com/workstation/VMware-workstation-full-17.5.1-23298084.exe" -OutFile VMware.exe

    - name: Install VMware Workstation silently
      run: |
        .\VMware.exe /s /v"/qn EULAS_AGREED=1 AUTOSOFTWAREUPDATE=0 DESKTOP_SHORTCUT=0"

    - name: Download EVE-NG ISO
      run: Invoke-WebRequest "https://customers.eve-ng.net/eve-ce-prod-6.2.0-4-full.iso" -OutFile eve-ng.iso
